### ISSUE TITLE
Worker nodes never get upgraded kubeadm

### ISSUE THREAD

**Issue by bravomail** [PeeK1e/kubeadm-upgrade#2]
I searched and double checked. You only upgrade kubeadm on controlplane/master nodes.
K8s docs says you should do it on "all nodes".
Hence, "kubeadm upgrade node"  might eventually fail on worker nodes.

**Comment by PeeK1e** [comment]
Hey,
I guess that you refer to the `upgrade-node` role. 
The worker nodes have an seperate page about upgrading them. See here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/

The upgrade process is roughly this (leaving out the package upgrades, draining, etc.)
1. run `kubeadm upgrade plan` and `kubeadm upgrade apply <planned-version>` on the first control-plane
2. run `kubeadm upgrade plan` and `kubeadm upgrade node` on the other control planes
3. run `kubeadm upgrade node` on the worker nodes

Of course i might have missed something but the docs describe the process for worker nodes as seen above

**Comment by PeeK1e** [comment]
closing this since there is no actitivy
